USE a21enrbonstr_plasticprecios;

CREATE TABLE IF NOT EXISTS GENERICUSER(
    code INT PRIMARY KEY AUTO_INCREMENT,
    nick VARCHAR(30) NOT NULL,
    pwd VARCHAR(30) NOT NULL,
    rol VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS SUPERUSER(
    code INT PRIMARY KEY,
    FOREIGN KEY (code) REFERENCES GENERICUSER (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ADMINISTRATOR(
    code INT PRIMARY KEY,
    FOREIGN KEY (code) REFERENCES GENERICUSER (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS COMMONUSER(
    code INT PRIMARY KEY,
    FOREIGN KEY (code) REFERENCES GENERICUSER (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ARTIST(
    code INT PRIMARY KEY,
    img VARCHAR(200),
    descr TEXT,
    FOREIGN KEY (code) REFERENCES GENERICUSER (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SENDING(
    code INT PRIMARY KEY AUTO_INCREMENT,
    subject VARCHAR(200),
    message TEXT,
    dateOfMessage DATE,
    sender INT,
    recipient INT,
    FOREIGN KEY (sender) REFERENCES GENERICUSER (code)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
    FOREIGN KEY (recipient) REFERENCES GENERICUSER (code)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    code INT PRIMARY KEY AUTO_INCREMENT,
    creator INT,
    price FLOAT UNSIGNED,
    img VARCHAR(200),
    localization VARCHAR(200),
    name VARCHAR(50),
    descr TEXT,
    FOREIGN KEY (creator) REFERENCES ARTIST (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ARTISTCOMMENTS(
    code INT PRIMARY KEY,
    artist INT,
    FOREIGN KEY (artist) REFERENCES ARTIST (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUCTCOMMENTS(
    code INT PRIMARY KEY AUTO_INCREMENT,
    product INT,
    descr TEXT,
    FOREIGN KEY (product) REFERENCES PRODUCT (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS WISHLIST(
    user INT,
    product INT,
    PRIMARY KEY (user, product),
    FOREIGN KEY (user) REFERENCES GENERICUSER (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (product) REFERENCES PRODUCT (code)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);